name: Determine docs version
description: |
  Discriminate between stable (last tag) and latest (most recent default branch)
  versions

outputs:
  version:
    description: "The discriminated version"
    value: ${{ steps.classify.outputs.version }}

runs:
  using: composite

  steps:
    - id: classify
      shell: bash
      run: |
        if [[ "${{ github.ref  }}" == "refs/heads/main" ]]; then
              echo "version=latest" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ github.ref_type }}" == "branch" ]] && [[ "${{ github.ref  }}" != "refs/heads/main" ]]; then
              exit 1
        fi
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
              echo "version=stable" >> $GITHUB_OUTPUT
        fi
