name: Build the documentation

on:
  workflow_call:
    inputs:
      python-version:
        description: "Used python version"
        required: true
        type: string
      dependency-path:
        description: "Path to the dependency file"
        required: true
        type: string
      path-doc:
        description: "Documentation path"
        required: false
        type: string
        default: ./doc
      poetry-extras:
        description: "poetry extra flags"
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache-dependency-path: ${{ inputs.dependency-path }}
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          poetry install --no-interaction ${{ inputs.poetry-extras }}
          pip install poethepoet
      - name: Compile docs
        run: |
          poe docs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ inputs.path-doc }}/build/html
