name: Build the documentation

on:

  workflow_call:
    inputs:
        python-version:
          description: 'Used python version'
          required: true
          type: string
        package-manager:
          description: 'pip or poetry'
          required: true 
          type: string
        dependency-path:
          description: 'Path to the dependency file'
          required: true 
          type: string
        path-doc:
          description: 'Documentation path'
          required: false
          type: string 
          default: ./doc
        poetry-extras:
          description: 'poetry extra flags'
          required: false
          type: string
          default: ""
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
        if: ${{ inputs.package-manager == 'poetry' }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: ${{ inputs.package-manager }}
          cache-dependency-path: ${{ inputs.dependency-path }} 
      - name: Install dependencies and compile the documentation with pip
        run: |
          pip install .[docs]
          # required by nbsphinx
          # https://nbsphinx.readthedocs.io/en/0.2.15/installation.html#pandoc
          sudo apt install pandoc
          cd ${{ inputs.path-doc }}
          make html
        if : ${{ inputs.package-manager == 'pip' }}
      - name: Install dependencies and compile the documentation with poetry
        run: |
          sudo apt install pandoc
          poetry config installer.modern-installation false
          poetry install --no-interaction ${{ inputs.poetry-extras }}
          pip install poethepoet
          poe docs
        if: ${{ inputs.package-manager == 'poetry' }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ inputs.path-doc }}/build/html
  
