name: Deploy

on:

  workflow_call:
    inputs:
        os:
          description: 'Used operation system'
          required: true
          type: string
        python-version:
          description: 'Used python version'
          required: true
          type: string
        publish:
          description: 'Publish the docs'
          required: false
          type: boolean
          default: false
    secrets:
      PYPI-TOKEN:
        required: false


jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Build wheels
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Store wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist
    - name: Publish distribution to PyPI
      if: ${{ inputs.publish }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
