name: Build the documentation

on:
  workflow_call:
    inputs:
      python-version:
        description: "Used python version"
        required: true
        type: string
      poetry-extras:
        description: "poetry extra flags"
        required: false
        type: string
        default: ""
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: qiboteam/workflows/actions/poetry/setup@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install project
        run: poetry install ${{ inputs.poetry-extras }}
      - name: Install dependencies and compile the documentation with poetry
        run: |
          sudo apt install pandoc
          poe docs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc/build/html
