name: Deploy

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false
      poetry-extras:
        required: false
        type: string
        default: ""
      doctest:
        required: false
        type: boolean
        default: false
    secrets:
      PYPI-TOKEN:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Disable modern installer
        run: poetry config installer.modern-installation false
      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install project
        run: poetry install --no-interaction ${{ inputs.poetry-extras }}
      - name: Install task runner
        run: pip install poethepoet
      - name: Test
        run: |
          source $VENV
          poe test
      - name: Test documentation examples
        if: ${{ inputs.doctests }}
        run: |
          source $VENV
          make -C doc doctest
      - name: Package the distribution
        run: |
          poetry build
      - name: Publish distribution to PyPI
        if: ${{ inputs.publish }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
