name: CI


on:
 
  push:
    branches: [ "main","better_workflow" ]


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
        with:
          clean: False

      - name: Clone qibo repository
        uses: actions/checkout@v2
        with:
          repository: qiboteam/qibo

      - name: Deploy documentation
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install .[docs]
      
      
