name: Wheels

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        default: false
      poetry-extras:
        required: false
        type: string
        default: ""
      doctest:
        required: false
        type: boolean
        default: false
    secrets:
      PYPI-TOKEN:
        required: false

jobs:
  build:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: qiboteam/workflows/actions/poetry/setup@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install project
        run: poetry install ${{ inputs.poetry-extras }}
      - name: Package the distribution
        run: |
          # package the pure python wheel
          poetry build
      - name: Publish distribution to PyPI
        if: ${{ inputs.publish }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
